server:
  port: 8080
spring:
  application:
    name: takeout
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://database-1.cgvvzu2dpz2h.ap-southeast-4.rds.amazonaws.com:3306/takeout
      username: root
      password: 3KLEKlAxQulgjYmj8XzE
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
amazon:
  s3bucket:
    bucketName: mytakeoutapp
    accessKey: AKIASEK4W7UEZ3AEEIW7
    secretKey: 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
    region: ap-east-1
#takeout:
#  path: .\img\